# Note if you are trying to deploy on vps then directly fill values in ("")

from os import getenv

# VPS --- FILL COOKIES 🍪 in """ ... """ 

INST_COOKIES = """
# wtite up here insta cookies
"""

YTUB_COOKIES = """
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
#HttpOnly_.youtube.com	TRUE	/	TRUE	1779290552	__Secure-3PSID	g.a000vwhzjF89yFmDfDUdjwzTVZVy3o9fKZSAmKSMBSfK0Mj1LDBaRoLwnb13uqZKk2Z6c0AFgQACgYKAbASARESFQHGX2Mi7UOCXJzFtYYwyT19BZiuxBoVAUF8yKrq0q2eay9HJt8d5HONeJbt0076
.youtube.com	TRUE	/	FALSE	1776477686	SIDCC	AKEyXzXlHvYhwSVdBteiHSXuCifuoI0rBPBwZlRDr2zEfzLyzjBWm7lBNROW8g7IDYzHaMmcjQ
.youtube.com	TRUE	/	FALSE	1779290552	SID	g.a000vwhzjF89yFmDfDUdjwzTVZVy3o9fKZSAmKSMBSfK0Mj1LDBac-eNMfzRviGQAJgDMKzBKAACgYKAfASARESFQHGX2MikBDxw7NbLPWmxLgC_U_TERoVAUF8yKrAU3D76-2klGJBMSTE5kkg0076
#HttpOnly_.youtube.com	TRUE	/	TRUE	1776477685	__Secure-1PSIDTS	sidts-CjEB7pHptZKRRyDvhWQAnAJuTsXN6QodVaDVN1Lz8SOPHZnI9-UWCL-SEU1MiCtV2-FzEAA
.youtube.com	TRUE	/	TRUE	1779290552	SAPISID	_ZT2IAhPhmAsstUX/ACvlur0Cugjbupx0M
#HttpOnly_.youtube.com	TRUE	/	TRUE	1776477686	__Secure-1PSIDCC	AKEyXzXY6sHLoyuQKxySJZOhzwgWUNKskda0zeBMYd3a-KNKT4jIp0oMII9annCrcnrJ38WAEw
#HttpOnly_.youtube.com	TRUE	/	TRUE	1779290552	SSID	AfsawV6yxzB2c2qwh
.youtube.com	TRUE	/	TRUE	1779290552	__Secure-1PAPISID	_ZT2IAhPhmAsstUX/ACvlur0Cugjbupx0M
#HttpOnly_.youtube.com	TRUE	/	TRUE	1779290552	__Secure-1PSID	g.a000vwhzjF89yFmDfDUdjwzTVZVy3o9fKZSAmKSMBSfK0Mj1LDBaxH8eA0oJt2kPT21lvR1yawACgYKASUSARESFQHGX2MidKwNoYF6KiyW518dpyfS9xoVAUF8yKrg5JNFybYh9TLNqEFMhKyy0076
.youtube.com	TRUE	/	TRUE	1779290552	__Secure-3PAPISID	_ZT2IAhPhmAsstUX/ACvlur0Cugjbupx0M
#HttpOnly_.youtube.com	TRUE	/	TRUE	1776477686	__Secure-3PSIDCC	AKEyXzWndyqf5YORoDc8J6PmUgp0zmAGjVAkxmtjCKtNStyzfgTBPRywKlQmBNSVTB4giyVVsg
#HttpOnly_.youtube.com	TRUE	/	TRUE	1776477685	__Secure-3PSIDTS	sidts-CjEB7pHptZKRRyDvhWQAnAJuTsXN6QodVaDVN1Lz8SOPHZnI9-UWCL-SEU1MiCtV2-FzEAA
.youtube.com	TRUE	/	FALSE	1779290552	APISID	j82Dofy0h04lSlte/AT3eK4lphapEYiD6G
#HttpOnly_.youtube.com	TRUE	/	FALSE	1779290552	HSID	AnWSJxrLLOZGKjYmI
#HttpOnly_.youtube.com	TRUE	/	TRUE	1779297207	LOGIN_INFO	AFmmF2swRQIhAPA-HdFyvNga2w5-4UNiRRSVzqETdPD-CSThYsxPzNoBAiB8lAF44JDIXgdk8SZIxCJGbq7dNokNCDClPD3ceMi-ng:QUQ3MjNmeXc3aG5HUzBIV1IxVTZ0SEgzOGlZb1QxVDgwblZERFczRTg1MzY2RFEwVzk2Y0FIblRmTzhCbXdYRFp2OFVneDNFdlhZTFlMVko0SUhQSmpiU1BleW13b1hJN0JtYVFwaENsYTk2M3NEUFF1OHlacVltUk1FVmJCYVFwbEdCYjFhZ2k0aFkzd2s1WDBZU0FwWnlGemJtanV6d1V3
.youtube.com	TRUE	/	TRUE	1779501681	PREF	tz=Asia.Dhaka&f6=40000000
"""

API_ID = int(getenv("API_ID", "28239710"))
API_HASH = getenv("API_HASH", "7fc5b35692454973318b86481ab5eca3")
BOT_TOKEN = getenv("BOT_TOKEN", "7809622003:AAGnBd0wkHuMo88DyW0VF-GrHQdUc3I9ylI")
OWNER_ID = list(map(int, getenv("OWNER_ID", "7303810912").split()))
MONGO_DB = getenv("MONGO_DB", "mongodb+srv://ytpremium4434360:zxx1VPDzGW96Nxm3@itssmarttoolbot.dhsl4.mongodb.net/?retryWrites=true&w=majority&appName=ItsSmartToolBot")
LOG_GROUP = getenv("LOG_GROUP", "-1002224822353")
CHANNEL_ID = int(getenv("CHANNEL_ID", "-1002224203739"))
FREEMIUM_LIMIT = int(getenv("FREEMIUM_LIMIT", "0"))
PREMIUM_LIMIT = int(getenv("PREMIUM_LIMIT", "500"))
WEBSITE_URL = getenv("WEBSITE_URL", "upshrink.com")
AD_API = getenv("AD_API", "52b4a2cf4687d81e7d3f8f8e78cb")
STRING = getenv("STRING", None)
YT_COOKIES = getenv("YT_COOKIES", YTUB_COOKIES)
DEFAULT_SESSION = getenv("DEFAUL_SESSION", None)  # added old method of invite link joining
INSTA_COOKIES = getenv("INSTA_COOKIES", INST_COOKIES)
